# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: Bugtree
google_analytics: Bugtree
title: Bugtree
exclude: [vendor]

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Bugtree

description: The Docs. Read them. 
author:
  name: Marcos Valle
  email: marcosvalle@protonmail.com
  github: marcosValle
  twitter: _mvalle_
  linkedin: mvallecyber
  bio: Born to kill bugs. Live by them.
  email_md5: 1df7ec002d2e576bae0ee492c97e82b8 

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
